# Generated by Django 2.1.5 on 2019-10-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('au_name', models.CharField(max_length=48)),
                ('au_id', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=128)),
                ('b_author', models.CharField(max_length=50)),
                ('b_content', models.TextField()),
                ('b_pub_date', models.DateField(auto_now=True)),
                ('b_upd_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
