# Generated by Django 2.1.5 on 2019-10-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='b_read_vol',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='b_thumbs',
            field=models.IntegerField(default=0, verbose_name='点赞量'),
        ),
    ]
