# Generated by Django 2.1.5 on 2019-10-21 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='b_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authorinfo',
            name='au_name',
            field=models.CharField(max_length=48, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='b_title',
            field=models.CharField(max_length=128, verbose_name='博客标题'),
        ),
    ]
