# Generated by Django 2.1.5 on 2019-10-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191022_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_address', models.ImageField(upload_to='blog')),
            ],
        ),
    ]
