# Generated by Django 2.1.5 on 2019-10-28 13:44

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191028_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='b_content',
            field=mdeditor.fields.MDTextField(verbose_name='博客内容'),
        ),
    ]
