# Generated by Django 2.1.5 on 2019-10-28 16:28

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191028_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloginfo',
            old_name='b_pic',
            new_name='b_cover',
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='b_content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='b_introduction',
            field=models.CharField(max_length=128),
        ),
    ]
