# Generated by Django 2.1.5 on 2019-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=48, unique=True, verbose_name='作者')),
                ('u_id', models.CharField(blank=True, max_length=24)),
                ('u_password', models.CharField(max_length=48, verbose_name='密码')),
                ('u_email', models.CharField(max_length=100, unique=True, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
